name: smart_energy_pay
description: "Smart Energy Pay App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ^3.5.3

dependencies:
  awesome_snackbar_content: ^0.1.2
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.3
  country_flags: ^3.0.0
  country_picker: ^2.0.26
  country_state_city_pro: ^0.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  draggable_home: ^1.0.5
  either_dart: ^0.3.0
  excel: ^4.0.6
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_quill: ^10.8.5
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_stripe: ^11.4.0
  flutter_svg: ^1.1.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  image: ^3.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  jwt_decode: ^0.3.1
  liquid_pull_to_refresh: ^3.0.1
  local_auth: ^2.3.0
  lottie: ^3.2.0
  mailer: ^6.4.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.8.4
  percent_indicator: ^4.2.2
  pinput: ^5.0.1
  provider: ^6.1.2
  razorpay_flutter: 1.4.0
  share_plus: ^11.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_charts: ^27.1.56
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.gif"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: OCRA
      fonts:
        - asset: assets/Fonts/ocr-a.ttf
          weight: 100
    - family: RobotoMono
      fonts:
        - asset: assets/Fonts/RobotoMono-Regular.ttf
          weight: 300
